name: dune-tests
run-name: DUNE Rucio tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DUNERucioPolicy
        uses: actions/checkout@v7
        with:
          path: DUNERucioPolicy
      - name: Checkout Rucio
        uses: actions/checkout@v7
        with:
          repository: rucio/rucio
          path: rucio
      - name: Add MetaCat container
        shell: bash
        run: |
          COMPOSE_FILENAME=$GITHUB_WORKSPACE/rucio/etc/docker/dev/docker-compose.yml
          echo '  metacat:' >> $COMPOSE_FILENAME
          echo '    image: docker.io/jamespepcc/metacat_test' >> $COMPOSE_FILENAME
          echo '    ports:' >> $COMPOSE_FILENAME
          echo '      - "127.0.0.1:8000:8080"' >> $COMPOSE_FILENAME
          echo 'Modified compose file:'
          cat $COMPOSE_FILENAME
      - name: Start Rucio containers
        shell: bash
        run: docker compose -f $GITHUB_WORKSPACE/rucio/etc/docker/dev/docker-compose.yml --profile storage up -d
      - name: Initialise tests in container
        shell: bash
        run: docker exec -t dev-rucio-1 tools/run_tests.sh -ir
      - name: Stop containers
        shell: bash
        run: docker compose -f $GITHUB_WORKSPACE/rucio/etc/docker/dev/docker-compose.yml --profile storage down
