name: dune-tests
run-name: DUNE Rucio tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DUNERucioPolicy
        uses: actions/checkout@v7
        with:
          path: DUNERucioPolicy
      - name: Checkout Rucio
        uses: actions/checkout@v7
        with:
          repository: rucio/rucio
          path: rucio
      - name: Check file system layout
        shell: bash
        run: |
          # This echoes /home/runner/work/DUNERucioPolicy/DUNERucioPolicy
          echo $GITHUB_WORKSPACE

          # We're in $GITHUB_WORKSPACE here
          pwd

          # This lists the files that are part of the policy package repo
          # i.e. it's as if the checkout was run at /home/runner/work/DUNERucioPolicy
          echo "Contents of workspace:"
          ls
          echo "Contents of DUNERucioPolicy:"
          ls DUNERucioPolicy
          echo "Contents of rucio:"
          ls rucio
      - name: Check that we have docker-compose
        shell: bash
        run: docker compose
